dems/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('home.urls')),
url(r'^login/', include('login.urls')),
    url(r'^logout/', include('logout.urls')),
]

home/urls.py
from django.conf.urls import url
from . import views
app_name = 'home'
urlpatterns = [
    url(r'^', views.index,name='index'),
]

login/urls.py
from django.conf.urls import url
from . import views
app_name = 'login'
urlpatterns = [
    url(r'^remove/(?P<obj>[0-9]+)',views.remove,name='remove'),
    url(r'^(?P<obj_id>[0-9]+)/done', views.done,name='done'),
    url(r'^(?P<obj_id>[0-9]+)',views.save,name='save'),
    url(r'^', views.index,name='index'),
]

logout/urls.py
from django.conf.urls import url
from . import views
app_name = 'logout'
urlpatterns = [
    url(r'^(?P<obj_id>[0-9]+)/done',views.done,name='done'),
    url(r'^', views.index,name='index'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from django.http import Http404
# Create your views here.

def index(request):
	return render(request,'home/index.html',{})

home/templates/home/index.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Handlee|Josefin+Sans:300,600&amp;display=swap'><link rel="stylesheet" href="{%static 'home/style.css'%}">

<div class="container">
  <div class="card-wrap">
    <div class="card border-0 shadow card--welcome is-show" id="welcome">
      <div class="card-body">
        <h2 class="card-title">WELCOME</h2>
        <p>Welcome to the page</p>
        <div class="btn-wrap"><a class="btn btn-lg btn-register js-btn" data-target="register" href = '{%url 'login:index'%}';">CHECK IN</a><a class="btn btn-lg btn-login js-btn" data-target="login" href = '{%url 'logout:index'%}';">CHECK OUT</a></div>
      </div>
    </div>
  </div>
</div>
<!-- partial -->
  <script  src="{%static 'home/script.js'%}"></script>

home/templates/home/index2.html
<button type="button" onclick="window.location.href = '{%url 'login:index'%}';">CHECK_IN</button>
<button type="button" onclick="window.location.href = '{%url 'logout:index'%}';">CHECK_OUT</button>