dems/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('home.urls')),
url(r'^login/', include('login.urls')),
    url(r'^logout/', include('logout.urls')),
]

home/urls.py
from django.conf.urls import url
from . import views
app_name = 'home'
urlpatterns = [
    url(r'^', views.index,name='index'),
]

login/urls.py
from django.conf.urls import url
from . import views
app_name = 'login'
urlpatterns = [
    url(r'^remove/(?P<obj>[0-9]+)',views.remove,name='remove'),
    url(r'^(?P<obj_id>[0-9]+)/done', views.done,name='done'),
    url(r'^(?P<obj_id>[0-9]+)',views.save,name='save'),
    url(r'^', views.index,name='index'),
]

login/models.py
from django.db import models
from django.utils import timezone

class visitor(models.Model):
	firstname = models.CharField(max_length=250)
	lastname = models.CharField(max_length=250)
	email = models.CharField(max_length=250)
	phone_num = models.CharField(max_length=250)
	check_in = models.DateTimeField(default = timezone.now(), blank=True)
	check_out = models.DateTimeField(blank=True , default = timezone.now())
	status = models.BooleanField(default=True)

	def __str__(self):
		return self.firstname+" "+self.lastname+" "+str(self.pk);

class host(models.Model):
	visitor = models.ForeignKey(visitor,on_delete=models.CASCADE)
	firstname = models.CharField(max_length=250)
	lastname = models.CharField(max_length=250)
	email = models.CharField(max_length=250)
	phone_num = models.CharField(max_length=250)

	def __str__(self):
		return self.firstname+" "+self.lastname;

class currently_login(models.Model):
	visitor_firstname = models.CharField(max_length=250)
	visitor_lastname = models.CharField(max_length=250)
	visitor_email = models.CharField(max_length=250)
	visitor_phone_num = models.CharField(max_length=250)
	host_firstname = models.CharField(max_length=250)
	host_lastname = models.CharField(max_length=250)
	host_email = models.CharField(max_length=250)
	host_phone_num = models.CharField(max_length=250)

login/forms.py
from django import forms
from . import views
from django.core.validators import RegexValidator

class checkin_vis(forms.Form):
	firstname= forms.CharField(validators=[RegexValidator(regex=r'^\w+$',message='Enter valid first name',code='invalid_firstname')],max_length=100,widget= forms.TextInput(attrs={'placeholder':'Enter your first name'}))
	lastname= forms.CharField(validators=[RegexValidator(regex=r'^\w+$',message='Enter valid last name',code='invalid_lastname')],max_length=100,widget= forms.TextInput(attrs={'placeholder':'Enter your last name'}))
	email= forms.CharField(validators=[RegexValidator(regex=r'^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$',message='Enter valid email',code='invalid_email')],max_length=100,widget= forms.EmailInput(attrs={'placeholder':'Enter your email'}))
	phonenumber= forms.CharField(validators=[RegexValidator(regex=r'^[2-9]{2}[0-9]{8}',message='Enter valid phone number',code='invalid_firstname')],max_length=100,widget= forms.TextInput(attrs={'placeholder':'Enter phone number'}))

	#def clean_firstname(self,*args,**kwargs):
	#	firstname = self.cleaned_data.get('firstname')
	#	if '3rx' not in firstname:
	#		raise forms.ValidationError("NOT Valid first name")
	#	return firstname

class checkin_host(forms.Form):
	firstname= forms.CharField(validators=[RegexValidator(regex=r'^\w+$',message='Enter valid first name',code='invalid_firstname')],max_length=100,widget= forms.TextInput(attrs={'placeholder':'Enter your first name'}))
	lastname= forms.CharField(validators=[RegexValidator(regex=r'^\w+$',message='Enter valid last name',code='invalid_lastname')],max_length=100,widget= forms.TextInput(attrs={'placeholder':'Enter your last name'}))
	email= forms.CharField(validators=[RegexValidator(regex=r'^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$',message='Enter valid email',code='invalid_email')],max_length=100,widget= forms.EmailInput(attrs={'placeholder':'Enter your email'}))
	phonenumber= forms.CharField(validators=[RegexValidator(regex=r'[2-9]{2}[0-9]{8}',message='Enter valid phone number',code='invalid_firstname')],max_length=100,widget= forms.TextInput(attrs={'placeholder':'Enter phone number'}))

login/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import visitor,host,currently_login
from django.http import Http404
from . import forms
from . import send_mail
from . import sms
import _thread

def remove(request,obj):
	obj_ = visitor.objects.get(pk = obj)
	obj_.delete()
	obj__ = currently_login.objects.get(email = obj_.email)
	obj__.delete()
	return redirect('login:index')

def index(request):
	form = forms.checkin_vis()
	if request.method=='POST':
		form = forms.checkin_vis(request.POST,request.FILES)
		if form.is_valid():
			firstname = form.cleaned_data['firstname']
			lastname = form.cleaned_data['lastname']
			email = form.cleaned_data['email']
			phonenumber = form.cleaned_data['phonenumber']
			obj = visitor()	
			obj.firstname = firstname
			obj.lastname = lastname
			obj.email = email
			obj.phone_num = phonenumber
			li = visitor.objects.all().filter(email = email)
			for i in li:
				if i.status == True:
					return render(request,'login/index.html',{'form':form,'error':1})
			li = visitor.objects.all().filter(phone_num = phonenumber)
			for i in li:
				if i.status == True:
					return render(request,'login/index.html',{'form':form,'error':1})
			else:
				obj.save()
			return redirect('login:save',obj.pk)
	return render(request,'login/index.html',{'form':form,'error':0})

def save(request,obj_id):
	form = forms.checkin_host()
	if visitor.objects.filter(pk=obj_id).exists():
		pass
	else:
		raise Http404
	if host.objects.filter(visitor = visitor.objects.get(pk = obj_id)).exists():
		raise Http404
	if request.method=='POST':
		form = forms.checkin_host(request.POST)
		if form.is_valid():
			firstname = form.cleaned_data['firstname']
			lastname = form.cleaned_data['lastname']
			email = form.cleaned_data['email']
			phonenumber = form.cleaned_data['phonenumber']
			obj = host()
			obj.visitor = visitor.objects.get(pk=obj_id)
			obj.firstname = firstname
			obj.lastname = lastname
			obj.email = email
			obj.phone_num = phonenumber
			if obj.email == obj.visitor.email:
				return render(request,'login/save.html',{'pk':obj_id,'form':form,'error':1})
			elif obj.phone_num == obj.visitor.phone_num:
				return render(request,'login/save.html',{'pk':obj_id,'form':form,'error':2})
			elif host.objects.filter(visitor = obj.visitor).exists():
				return render(request,'login/save.html',{'pk':obj_id,'form':form,'error':3})
			else:
				mailing = send_mail.sending(obj)
				msg = sms.message(obj)
				try:
					_thread.start_new_thread(mailing.start,())
					pass
				except:
					print('Error occured while e-mailing at login(object_id= '+str(obj_id)+')')
				try:
					_thread.start_new_thread(msg.start,())
					pass
				except:
					print('Error occured while messaging at logout(object_id= '+str(obj_id)+')')
				obj.save()
				temp = currently_login()
				temp.visitor_firstname = obj.visitor.firstname
				temp.visitor_lastname = obj.visitor.lastname
				temp.visitor_email = obj.visitor.email
				temp.visitor_phone_num = obj.visitor.phone_num
				temp.host_firstname = obj.firstname
				temp.host_lastname = obj.lastname
				temp.host_email = obj.email
				temp.host_phone_num = obj.phone_num
				temp.save()
				return redirect('login:done',obj_id)
	return render(request,'login/save.html',{'pk':obj_id,'form':form,'error':0})

def done(request,obj_id):
	if visitor.objects.filter(pk=obj_id).exists():
		pass
	else:
		raise Http404
	if visitor.objects.get(pk=obj_id).status == False:
		return redirect('logout:done',obj_id)
	else:
		return render(request,'login/done.html',{})

login/templates/login/done.html
<!DOCTYPE html>
{% load static %}
  <meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Handlee|Josefin+Sans:300,600&amp;display=swap'><link rel="stylesheet" href="{%static 'login/style_login.css'%}">
<!-- partial:index.partial.html -->
<div class="container">
  <div class="card-wrap">
    
    <div class="card border-0 shadow card--register is-show" id="register">
      <div class="card-body">
		<h2 class="card-title">You are checked In.</h2>
       		<button class="btn btn-lg" onclick="window.location.href = '{%url 'home:index'%}';">Done</button>
      </div>
    </div>
  </div>
</div>
<!-- partial -->
  <script  src="{%static 'login/script_login.js'%}"></script>

login/templates/login/index(copy).html
<form action ='{% url 'login:transis' %}' method='POST'>
	{% csrf_token %}
	{{form}}
	<input type='submit'>
</form>

login/templates/login/index.html
<!DOCTYPE html>
{% load static %}
  <meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Handlee|Josefin+Sans:300,600&amp;display=swap'><link rel="stylesheet" href="{%static 'login/style_login.css'%}">
<!-- partial:index.partial.html -->
<div class="container">
  <div class="card-wrap">
    
    <div class="card border-0 shadow card--register is-show" id="register">
      <div class="card-body">
        <h2 class="card-title">Check In Details</h2>
        <p class="card-text">Enter your personal details</p>
        <form method='POST'>
	{%csrf_token%}
	{%ifequal error 1%} 
		<p class="error_text">Already checkin.</p>
	{%endifequal%}
	{% if form.errors %}
	{%for field in form%}
	{% for error in field.errors%}
	<p class="error_text">{{error}}</p>
	{%endfor%}
	{%endfor%}
	{% endif %}
          {%for field in form%}
		<div class="form-group">
		{{field}}<br>
		</div>
		{%endfor%}
          <input class="btn btn-lg" type='Submit'></input>
        </form>
      </div>
      <a class="btn btn-back js-btn" href="{%url 'home:index'%}"><i class="fas fa-angle-left"></i></button>
    </div>
  </div>
</div>
<!-- partial -->
  <script  src="{%static 'login/script_login.js'%}"></script>

login/templates/login/save (copy).html
<form action ='{% url 'login:save' pk%}' method='POST'>
	{% csrf_token %}
	{{form}}
	<input type='submit'>
</form>

login/templates/login/save(secnd_copy).html
<!DOCTYPE html>
{% load static %}
  <meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Handlee|Josefin+Sans:300,600&amp;display=swap'><link rel="stylesheet" href="{%static 'login/style_login.css'%}">

<!-- partial:index.partial.html -->
<div class="container">
  <div class="card-wrap">
    
    <div class="card border-0 shadow card--register is-show" id="register">
      <div class="card-body">
        <h2 class="card-title">Check In Details</h2>
        <p class="card-text">Enter host details</p>
        <form action ='{% url 'login:save' pk%}' method='POST'>
	{%csrf_token%}
	{% if form.errors %}
	{%for field in form%}
	{% for error in field.errors%}
	<p class="error_text">{{error}}</p>
	{%endfor%}
	{%endfor%}
	{% endif %}
          {%for field in form%}
		<div class="form-group">
		{{field}}<br>
		</div>
		{%endfor%}
          <input class="btn btn-lg" type='Submit'></input>
        </form>
      </div>
      <a class="btn btn-back js-btn" href="{%url 'login:remove' pk%}"><i class="fas fa-angle-left"></i></button>
    </div>
  </div>
</div>
<!-- partial -->
  <script  src="{%static 'login/script_login.js'%}"></script>

login/templates/login/save.html
<!DOCTYPE html>
{% load static %}
  <meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Handlee|Josefin+Sans:300,600&amp;display=swap'><link rel="stylesheet" href="{%static 'login/style_login.css'%}">

<!-- partial:index.partial.html -->
<div class="container">
  <div class="card-wrap">
    
    <div class="card border-0 shadow card--register is-show" id="register">
      <div class="card-body">
        <h2 class="card-title">Check In Details</h2>
        <p class="card-text">Enter host details</p>
        <form  method='POST'>
	{%csrf_token%}
	{%ifequal error 1%} 
		<p class="error_text">Cannot have same email's.</p>
	{%endifequal%}
	{%ifequal error 2%} 
		<p class="error_text">Cannot have same phone's.</p>
	{%endifequal%}
	{%ifequal error 3%} 
		<p class="error_text">Already Checkin.</p>
	{%endifequal%}
	{% if form.errors %}
	{%for field in form%}
	{% for error in field.errors%}
	<p class="error_text">{{error}}</p>
	{%endfor%}
	{%endfor%}
	{% endif %}
          {%for field in form%}
		<div class="form-group">
		{{field}}<br>
		</div>
	{%endfor%}
          <input class="btn btn-lg" type='Submit'></input>
        </form>
      </div>
      <a class="btn btn-back js-btn" href="{%url 'login:remove' pk%}"><i class="fas fa-angle-left"></i></button>
    </div>
  </div>
</div>
<!-- partial -->
  <script  src="{%static 'login/script_login.js'%}"></script>